[package]
name = "venator-app"
version = "0.0.0"
description = "A log and trace viewer for Rust tracing"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-rc.1", features = [] }

[dependencies]
bincode = { version = "1.3.3", default-features = false }
chrono = { version = "0.4.24", default-features = false, features = ["clock", "serde"] }
tauri = { version = "2.0.0-rc.1", features = [] }
serde = { version = "1.0.159", default-features = false, features = ["std", "derive"] }
serde_json = "1"
tokio = { version = "1.38.0", features = ["rt-multi-thread", "macros", "net"] }

venator-engine = { path = "../../venator-engine", features = ["persist"] }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
